disabled_rules:
- multiple_closures_with_trailing_closure # Trailing Closureを許可するため除外

- trailing_whitespace # 空白の改行を許可するため除外


# 変数名が１文字以上なら許可に変更
identifier_name:
 min_length: 1

# 1行の文字数が200超えると警告、300超えるとエラーにする
line_length:
- 200 # warning
- 300 # error
